Fix and update basic setup
mitchellh/vagrant-google pull request #257
Opened 2021-12-04 08:51 UTC by gdubicki

* quickstart example config was missing required `image_project_id`
  to work at all (see #234, #228),
* update the GCP setup instructions to their current web UI as of now,
* reorganize initial setup sections for readability,
* change headings a bit for consistency,
* fix minor typos, replace http links with https etc.

2021-12-04 09:54 UTC, gdubicki commented
Oops, I was wrong. The `image_project_id` is NOT required, but https://github.com/fog/fog-google was missing the project_id of the image_family I was trying to use - `rocky-linux-cloud` for `rocky-linux-8`...

2021-12-20 07:57 UTC, gdubicki commented
@Temikus ?

2021-12-20 09:01 UTC, Temikus requested changes
Thank you for your contribution ❤️ 

Only one concern here, please see comment.

2021-12-20 10:11 UTC, gdubicki commented on lib/vagrant-google/action/run_instance.rb
> +          rescue NoMethodError
Sorry, Ruby is not my first language. Corrected. :) Is this what you had in mind?

2021-12-21 23:26 UTC, Temikus commented on lib/vagrant-google/action/run_instance.rb
> +          rescue NoMethodError
No worries. Yep, this'll do :)

2021-12-21 23:27 UTC, Temikus approved these changes

2021-12-21 23:27 UTC, merged